config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#home"

  resources :dancers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :auditions, only: [:index]
  end

  resources :producers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :castings, only: [:new, :create, :index]
  end

  resources :castings, only: [:show, :edit, :update, :index] do
    resources :auditions, except: [:show]
  end

  resources :auditions, only: [:show] do
    resources :videos, only: [:create, :destroy]
    resources :dancer_auditions, only: [:create, :destroy]
  end

  get 'my_auditions', to: 'dancers#my_auditions', as: 'my_auditions'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/casting.rb
class Casting < ApplicationRecord
  belongs_to :producer
  has_one_attached :photo

  has_many :auditions, dependent: :destroy
  has_one_attached :video

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description_and_dancing_styles_and_location_and_deadline,
                  against: %i[title description dancing_style location deadline],
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :title, presence: true
  validates :description, presence: true
  validates :dancing_style, presence: true
  validates :deadline, presence: true
  validates :location, presence: true
end

app/controllers/castings_controller.rb
class CastingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_casting, only: %i[show edit update destroy]

  def index
    if current_user.producer
      @producer = Producer.find(params[:producer_id])
      @castings = Casting.all.includes(:producer)
    else
      @castings = Casting.all
    end
  end

  def new
    @producer = current_user.producer
    @casting = Casting.new
  end

  def create
    @casting = Casting.new(casting_params)
    @casting.producer = current_user.producer
    if @casting.save
      redirect_to casting_path(@casting), notice: 'Casting was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @casting = Casting.find(params[:casting_id])
    if @casting.update(casting_params)
      redirect_to casting_path(@casting), notice: 'Casting was successfully updated.'
    else
      render :edit
    end
  end

  def edit
  end

  def show
    @producer = current_user.producer
    @same_style_castings = Casting.where(dancing_style: @casting.dancing_style).where.not(id: @casting.id)
  end

  def destroy
    @casting.destroy
    redirect_to root_path, notice: 'Casting was successfully destroyed.'
  end

  private

  def set_producer
    @producer = Producer.find(params[:producer_id])
  end

  def set_casting
    @casting = Casting.find(params[:id])
  end

  def casting_params
    params.require(:casting).permit(:title, :description, :dancing_style, :deadline, :location, :photo, :video)
  end
end

app/views/castings/edit.html.erb
<h1>Edit Cassting</h1>
<div class='background'>
  <div class='dancer-form-container'>
  <%= simple_form_for [@producer, @casting] do |f| %>
  <div class='form-group'>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :dancing_style %>
    <%= f.input :deadline %>
    <%= f.input :location %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, 'Update Casting', class: 'btn btn-primary' %>
     </div>
      <% end %>
  </div>
</div>

app/views/castings/index.html.erb
<% if current_user.producer %>
  <h1>This is all your castings</h1>

  <div class="container">
    <h1>Castings for <%= @producer.name %></h1>

    <% if @castings.any? %>
      <ul class="list-group">
        <% @castings.each do |casting| %>
          <li class="list-group-item">
            <h4><%= casting.title %></h4>
            <p><strong>Description:</strong> <%= casting.description %></p>
            <p><strong>Dancing Style:</strong> <%= casting.dancing_style %></p>
            <p><strong>Deadline:</strong> <%= casting.deadline %></p>
            <p><strong>Location:</strong> <%= casting.location %></p>
            <div class="btn-group">
              <%= link_to 'Show', producer_casting_path(@producer, casting), class: 'btn btn-primary mr-1' %>
              <%= link_to 'Edit', edit_producer_casting_path(@producer, casting), class: 'btn btn-primary mr-1' %>
              <%= link_to 'Destroy', producer_casting_path(@producer, casting), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No castings found.</p>
    <% end %>

    <%= link_to "Create New Casting", new_producer_casting_path(@producer), class: "btn btn-primary" %>
  </div>
<% else %>
  <div class="cards">
    <% @castings.each do |casting| %>
      <div class="card">
        <%= link_to casting_path(casting) do %>
          <div class="image-placeholder">
            <% if casting.photo.attached? %>
              <%= cl_image_tag casting.photo.key, class: 'card-image' %>
             <% end %>
           </div>
          <h2><%= casting.title %></h2>
           <div class="details">
             <span><%= casting.location %></span>
             <span><%= casting.dancing_style %></span>
          </div>
          <p><%= casting.description %></p>
          <div class="due-date"><%= casting.deadline %></div>
        <% end %>
       </div>
     <% end %>
  </div>

<% end %>

app/views/castings/new.html.erb
<div class='background'>
  <div class='casting-form-container'>
   <%= simple_form_for [@producer, @casting] do |f| %>
    <div class='form-group'>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :dancing_style %>
      <%= f.input :deadline %>
      <%= f.input :location %>
      <%= f.input :photo, as: :file %>
      <%= f.input :video, as: :file %>
      <%= f.button :submit, 'Create Casting', class: 'btn btn-flat' %>
    </div>
   <% end %>
  </div>
</div>

app/views/castings/show.html.erb
<head>
  <link rel="stylesheet" href="castings/_show.scss">
</head>
<body>
    <div class="container">
        <section class="main-content">
                <div class="job-description">
                    <div class="job-image">
                        <%= cl_image_tag @casting.photo.key, height: 300, width: 400, crop: :fill if @casting.photo.attached? %>
                    </div>
                    <div class="description">
                        <div class="producer-details">
                          <div class="producer-image">
                            <%= cl_image_tag @casting.producer.profile_picture.key, height: 50, width: 50, crop: :fill if @casting.producer.profile_picture.attached? %>
                          </div>
                        </div>
                        <h2><%= @casting.title %></h2>
                        <p><%= @casting.description %></p>
                        <div class="info-tags">
                            <span class="tag"><%= @casting.dancing_style %></span>
                        </div>
                        <div class="apply-details">
                          <span class="tag">📅  <%= @casting.deadline.strftime("%d %B, %Y") %></span>
                          <span class="tag">📍  <%= @casting.location %></span>
                        </div>

                          <div class="app">
                            <% if current_user.dancer %>
                            <div>
                              <%= link_to "Apply now", new_casting_audition_path(@casting), class: "btn btn-primary" %>
                            </div>
                            <% end %>

                            <% if current_user.producer? %>
                                <div class="auditions-link">
                                    <%= link_to "View All Auditions", casting_auditions_path(@casting), class: "btn btn-primary" %>
                                </div>
                            <% end %>
                          </div>

                        </div>
                </div>

            </div>
        </section>
        <section class="interested">
            <h3>You might also be interested in these</h3>
            <% if @same_style_castings.any? %>
                <% @same_style_castings.each do |same_style_casting| %>
                  <div class="card">
                    <%= link_to casting_path(same_style_casting) do %>
                      <div class="image-placeholder">
                        <% if same_style_casting.photo.attached? %>
                          <%= cl_image_tag same_style_casting.photo.key, class: 'card-image' %>
                        <% end %>
                      </div>
                    <h2><%= same_style_casting.title %></h2>
                        <div class="details">
                          <span><%= same_style_casting.location %></span>
                          <span><%= same_style_casting.dancing_style %></span>
                        </div>
                        <p><%= same_style_casting.description %></p>
                      <div class="due-date"><%= same_style_casting.deadline %></div>
                    <% end %>
                  </div>
                <% end %>
            <% else %>
              <p>No similar castings found.</p>
            <% end %>
        </section>
    </div>
</body>