config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#home"

  resources :dancers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :auditions, only: [:index]
  end

  resources :producers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :castings, only: [:new, :create, :index]
  end

  resources :castings, only: [:show, :edit, :update, :index] do
    resources :auditions, except: [:show]
  end

  resources :auditions, only: [:show] do
    resources :videos, only: [:create, :destroy]
    resources :dancer_auditions, only: [:create, :destroy]
  end

  get 'my_auditions', to: 'dancers#my_auditions', as: 'my_auditions'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    © 2024 Castify, Inc.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://t4.ftcdn.net/jpg/00/91/20/09/360_F_91200919_gUFH5eziwPuYmhRYL142qeuoimnra6g7.jpg" %>
    <% end %>

    <div class="mx-auto text-center">
      <h5 class="title mt-2">Castify</h5>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <% if current_user.role == "dancer" %>
            <li class="nav-item active">

              <% if current_user.dancer && current_user.dancer.id %>
                <%= link_to "Profile", dancer_path(current_user.dancer), class: "nav-link" %>
              <% else %>
                <%= link_to "Create Dancer Profile", new_dancer_path, class: "btn btn-flat" %>
              <% end %>
            </li>
          <% end %>

          <% if current_user.role == "dancer" %>
            <li class="nav-item active">
              <%= link_to "Auditions", my_auditions_path, class: "nav-link" %>
            </li>
          <% end %>


          <% if current_user.role == "producer" %>
            <li class="nav-item active">

              <% if current_user.producer && current_user.producer.id %>
                <%= link_to "Profile", producer_path(current_user.producer.id), class: "nav-link" %>
              <% else %>
                <%= link_to "Create Producer Profile", new_producer_path, class: "btn btn-flat" %>
              <% end %>
            </li>
          <% end %>

          <% if current_user.role == nil%>
            <li class="nav-item active">
              <%= link_to "Add more to your profile", edit_user_registration_path(current_user), class: "btn btn-flat" %>
            </li>
          <% end %>

          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.dancer && current_user.dancer.profile_picture.attached? %>
                  <%= cl_image_tag current_user.dancer.profile_picture.key, transformation: [{ width: 50, height: 50, crop: :limit }], class: "avatar" %>
              <% elsif current_user.producer && current_user.producer.profile_picture.attached? %>
                  <%= cl_image_tag current_user.producer.profile_picture.key, transformation: [{ width: 50, height: 50, crop: :limit }], class: "avatar" %>
              <% else %>
                <%= image_tag "https://img.freepik.com/free-vector/user-circles-set_78370-4704.jpg?w=740&t=st=1719342054~exp=1719342654~hmac=7519b53e7f960eb52fc5f6ed5e729593d0a0828ad103e0e1f370e48c85b0ab53", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>