config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#home"

  resources :dancers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :auditions, only: [:index]
  end

  resources :producers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :castings, only: [:new, :create, :index]
  end

  resources :castings, only: [:show, :edit, :update, :index] do
    resources :auditions, except: [:show]
  end

  resources :auditions, only: [:show] do
    resources :videos, only: [:create, :destroy]
    resources :dancer_auditions, only: [:create, :destroy]
  end

  get 'my_auditions', to: 'dancers#my_auditions', as: 'my_auditions'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/home.html.erb
  <div class="home-page">
    <div class="banner">
      <div class="container">
        <h1>Castify</h1>
        <p>Find your next gig</p>

        <% if current_user %>
          <% if current_user.producer %>
            <%= link_to "Create a Casting", new_producer_casting_path(current_user.producer), class: "btn" %>
          <% else %>
            <%= link_to "Apply now", castings_path, class: "btn" %>
          <% end %>
        <% else %>
          <%= link_to "Apply now", castings_path, class: "btn" %>
        <% end %>

      </div>
    </div>

  <div>
    <div class="search-bar">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search..." %>
        <%= submit_tag "Search", class: "btn btn-search" %>
      <% end %>
    </div>
  </div>

  <div>
      <div class="Cards-title">
        <% if current_user %>
          <% if current_user.producer %>
            <h3>Dancers</h3>
          <% else %>
            <h3>Available Castings</h3>
          <% end %>
        <% else %>
          <h3>Available Castings</h3>
        <% end %>
      </div>
  </div>

    <% if current_user && current_user.producer %>
      <div class="cards">
        <% @dancers.each do |dancer| %>
          <div class="card">
            <%= link_to dancer_path(dancer) do %>
                <% if dancer.profile_picture.attached? %>
                  <%= cl_image_tag dancer.profile_picture.key, class: 'card-image' %>
                <% end %>

              <div class="card-info">
              <h2><%= dancer.name %></h2>
              <div class="details">
                <span><%= dancer.dancing_styles %></span>
              </div>
              <p><%= dancer.bio %></p>
              </div>
            <% end %>
          </div>
        <% end %>
          </div>

    <% else current_user && current_user.dancer %>
      <div class="cards">
        <% @castings.each do |casting| %>
          <div class="card">
            <%= link_to casting_path(casting) do %>

                <% if casting.photo.attached? %>
                  <%= cl_image_tag casting.photo.key, class: 'card-image' %>
                <% end %>

              <div class="card-info">
              <h2><%= casting.title %></h2>
              <div class="details">
                <span><i class="fas fa-map-marker-alt icon"></i><%= casting.location %></span>
                <span><i class="fa-solid fa-person-running"></i> <%= casting.dancing_style %></span>
              </div>
              <p><%= casting.description %></p>

              <div class="due-date"><i class="fas fa-calendar-alt icon"></i><%= casting.deadline %></div>

          </div>
            <% end %>
      </div>
        <% end %>
    </div>
    <% end %>

  </div>