config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#home"

  resources :dancers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :auditions, only: [:index]
  end

  resources :producers, only: [:new, :create, :show, :edit, :update, :index] do
    resources :castings, only: [:new, :create, :index]
  end

  resources :castings, only: [:show, :edit, :update, :index] do
    resources :auditions, except: [:show]
  end

  resources :auditions, only: [:show] do
    resources :videos, only: [:create, :destroy]
    resources :dancer_auditions, only: [:create, :destroy]
  end

  get 'my_auditions', to: 'dancers#my_auditions', as: 'my_auditions'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_many :castings, dependent: :destroy
  belongs_to :user
  has_one_attached :profile_picture

  validates :name, presence: true
  validates :bio, presence: true
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_producer, only: %i[show edit update destroy]

  def new
    @producer = current_user.build_producer
  end

  def edit
    @producer = Producer.find(params[:id])
  end

  def show
    @producer = Producer.find(params[:id])
    @castings = @producer.castings

    if @castings.any?
      @auditions = @castings.map(&:auditions).flatten
    else
      @auditions = []
    end
  end

  def update
    @producer = Producer.find(params[:id])
    if @producer.update(producer_params)
      redirect_to @producer, notice: 'Producer was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @producer = current_user.build_producer(producer_params)
    if @producer.save
      redirect_to @producer, notice: 'Producer profile was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @producer = Producer.find(params[:id])
    @producer.destroy
    redirect_to producers_url, notice: 'Producer was successfully destroyed.'
  end

  private

  def set_producer
    @producer = Producer.find(params[:id])
  end

  def producer_params
    params.require(:producer).permit(:name, :bio, :profile_picture)
  end
end

app/views/producers/edit.html.erb
<div class='background'>
  <div class='producer-form-container'>
    <%= simple_form_for @producer do |f| %>
      <div class='form-group'>
      <%= f.input :name %>
      <%= f.input :bio %>
      <%= f.input :profile_picture, as: :file, label: 'Profile Picture' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.button :submit, 'Update Producer Profile',  class: 'btn btn-flat' %>
      </div>
    <% end %>
  </div>
</div>

app/views/producers/new.html.erb
<%= simple_form_for @producer do |f| %>
  <%= f.input :name %>
  <%= f.input :bio %>
  <%= f.input :profile_picture, as: :file, label: 'Profile Picture' %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.button :submit, 'Create Producer Profile' %>
<% end %>

app/views/producers/show.html.erb
<div class="producer-show-page">
  <div class="background">
    <div class="producer-info">
      <%= cl_image_tag @producer.profile_picture.key, height: 300, width: 400, crop: :fill if @producer.profile_picture.attached? %>
      <p><strong>Producer Name:</strong> <%= @producer.name %></p>
      <p><strong>Producer Bio:</strong> <%= @producer.bio %></p>
      <p><strong>Producer Email:</strong> <%= current_user.email %></p>
      <% if current_user.id == @producer.user_id %>
        <%= link_to "Update Profile", edit_producer_path(current_user.producer), class: "btn btn-flat" %>
      <% end %>
      <br>
      <% if current_user.id == @producer.user_id %>
        <%= link_to "Create New Casting", new_producer_casting_path(@producer), class: "btn btn-flat", style: "margin-top: 10px;" %>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <h2>Castings</h2>
  <% if @castings.any? %>
    <ul>
      <% @castings.each do |casting| %>
        <li>
          <%= link_to casting.title, casting_path(casting), class: "btn" %>
          <p><%= casting.description %></p>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No castings available.</p>
  <% end %>
</div>